window["formatPokemonJSON"]([
    {
        "name":"Bulbasaur",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/cWmVJDJ.png",
                "description":""
            }
        ]
    },
    {
        "name":"Ivysaur",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/oWYVt0l.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Venusaur",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/mlAqXMZ.png",
                "description":""
            }
        ]
    },
    {
        "name":"Charmander",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/IJ2v7hz.png",
                "description":"Found by Jericho Beach"
            }
        ]
    },
    {
        "name":"Charmeleon",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Charizard",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Squirtle",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/la7YesJ.png",
                "description":""
            }
        ]
    },
    {
        "name":"Wartortle",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/snmqzf1.png",
                "description":""
            },{
                "src":"http://i.imgur.com/ttPwaH0.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Blastoise",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/PAKaS5P.png",
                "description":""
            }
        ]
    },
    {
        "name":"Caterpie",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/XGgCZTq.png",
                "description":"Sitting outisde of Catfe"
            },{
                "src":"http://i.imgur.com/57g2DB6.png",
                "description":""
            }
        ]
    },
    {
        "name":"Metapod",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/g9Um1UU.png",
                "description":""
            }
        ]
    },
    {
        "name":"Butterfree",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/fKr0ng9.png",
                "description":"Sitting alone by the #7 Subway"
            }
        ]
    },    
    {
        "name":"Weedle",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/xdhs7Kg.png",
                "description":"Hanging by the escalator"
            }
        ]
    },
    {
        "name":"Kakuna",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/5DxugKw.png",
                "description":""
            }
        ]
    },
    {
        "name":"Beedrill",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/Y7b8V6Q.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Pidgey",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Pidgeotto",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/YdPlCKq.png",
                "description":""
            }
        ]
    },
    {
        "name":"Pidgeot",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/56FDqsO.jpg",
                "description":""
            },{
                "src":"http://i.imgur.com/jiNMH7S.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Rattata",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/ah0FwfR.png",
                "description":"Protecting owner's house"
            }
        ]
    },
    {
        "name":"Raticate",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/6Wq3ziu.png",
                "description":""
            }
        ]
    },
    {
        "name":"Spearow",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Fearow",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/CDIQY7z.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Ekans",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/9Mk4lPl.png",
                "description":""
            }
        ]
    },
    {
        "name":"Arbok",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Pikachu",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/hcrtfSh.png",
                "description":"Trying to photobomb"
            },{
                "src":"http://i.imgur.com/VPISPmd.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Raichu",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Sandshrew",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Sandslash",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Nidoran♀",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/4FWXYiw.png",
                "description":""
            }
        ]
    },
    {
        "name":"Nidorina",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/OFkf1Bc.png",
                "description":""
            }
        ]
    },
    {
        "name":"Nidoqueen",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Nidoran♂",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/IQVCesg.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Nidorino",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Nidoking",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/4BVhKGE.png",
                "description":""
            }
        ]
    },
    {
        "name":"Clefairy",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/HpTu2XR.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Clefable",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/oTbI58A.png",
                "description":""
            }
        ]
    },
    {
        "name":"Vulpix",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/CgnN9yf.png",
                "description":""
            }
        ]
    },
    {
        "name":"Ninetales",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Jigglypuff",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/6YzAnc5.png",
                "description":""
            }
        ]
    },
    {
        "name":"Wigglytuff",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/d5o4gkn.png",
                "description":""
            }
        ]
    },
    {
        "name":"Zubat",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/DfjVqlq.jpg",
                "description":""
            },{
                "src":"http://i.imgur.com/Ja0xSaF.png",
                "description":""
            }
        ]
    },
    {
        "name":"Golbat",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/W4jC2bY.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Oddish",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/FvXGhPH.png",
                "description":""
            }
        ]
    },
    {
        "name":"Gloom",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/FMZRs9h.png",
                "description":""
            }
        ]
    },
    {
        "name":"Vileplume",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/BmgsfSF.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Paras",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/CbFD2Sd.png",
                "description":""
            }
        ]
    },
    {
        "name":"Parasect",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/fPOkhGi.png",
                "description":""
            }
        ]
    },
    {
        "name":"Venonat",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/C6QM6bi.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Venomoth",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/lAtjBX7.png",
                "description":""
            }
        ]
    },
    {
        "name":"Diglett",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/ST8BXA3.png",
                "description":""
            }
        ]
    },
    {
        "name":"Dugtrio",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/RvuK92T.jpg",
                "description":""
            }
        ]
    },
    {
        "name":"Meowth",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/qkKvFjz.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Persian",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Psyduck",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Golduck",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/BrkPaCU.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Mankey",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/UBrqxDI.png",
                "description":""
            }
        ]
    },
    {
        "name":"Primeape",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/Nq7ZSza.png",
                "description":""
            }
        ]
    },
    {
        "name":"Growlithe",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/GXfBpR2.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Arcanine",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Poliwag",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Poliwhirl",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/UhDOZdN.png",
                "description":""
            }
        ]
    },
    {
        "name":"Poliwrath",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/LKU60nL.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Abra",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/ZikFUrE.png",
                "description":"Just chillin"
            }
        ]
    },
    {
        "name":"Kadabra",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/K2AKRa2.png",
                "description":"Trying to cast a spell on me"
            },{
                "src":"http://i.imgur.com/a8xcWWw.png",
                "description":"Enjoying some flowers"

            }
        ]
    },
    {
        "name":"Alakazam",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/hFhtvNK.png",
                "description":"Playing with some magic"
            }
        ]
    },    
    {
        "name":"Machop",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/vfTa94g.png",
                "description":""
            }
        ]
    },
    {
        "name":"Machoke",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/klB7ewW.png",
                "description":""
            }
        ]
    },
    {
        "name":"Machamp",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/GDiJqft.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Bellsprout",
        "date":"",
        "img":[
            {
                "src":"http://i.imgur.com/byibPvU.png",
                "description":""
            },{
                "src":"http://i.imgur.com/HAD4yNx.png",
                "description":""
            }
        ]
    },
    {
        "name":"Weepinbell",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/ymSWhyr.png",
                "description":""
            },
            {
                "src":"http://i.imgur.com/uAPqPkM.png",
                "description":""
            }
        ]
    },
    {
        "name":"Victreebel",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Tentacool",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Tentacruel",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/uEP94n4.png",
                "description":""
            },{
                "src":"http://i.imgur.com/wwtvAkF.png",
                "description":""
            }
        ]
    },
    {
        "name":"Geodude",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/YSQVDmN.png",
                "description":""
            }
        ]
    },
    {
        "name":"Graveler",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/KFyAbox.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Golem",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Ponyta",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/UaQzypH.png",
                "description":""
            },{
                "src":"http://i.imgur.com/nCJvm1A.png",
                "description":""
            }
        ]
    },
    {
        "name":"Rapidash",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Slowpoke",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/A2r5Vxs.png",
                "description":""
            }
        ]
    },
    {
        "name":"Slowbro",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/QMZDqzt.png",
                "description":""
            }
        ]
    },
    {
        "name":"Magnemite",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/PKJ62u2.png",
                "description":""
            }
        ]
    },
    {
        "name":"Magneton",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Farfetch d",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Doduo",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Dodrio",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Seel",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/Z0juPBD.png",
                "description":""
            }
        ]
    },
    {
        "name":"Dewgong",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/mle7WZh.png",
                "description":""
            }
        ]
    },
    {
        "name":"Grimer",
        "date":"",
        "img":[{
            "src":"http://i.imgur.com/dCUqs64.png",
            "description":""
            }
        ]
    },    
    {
        "name":"Muk",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Shellder",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Cloyster",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/cyS3O83.png",
                "description":""
            }
        ]
    },
    {
        "name":"Gastly",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/EVeLNr9.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Haunter",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/mYWXP2A.png",
                "description":""
            }
        ]
    },
    {
        "name":"Gengar",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/9gT8uyn.png",
                "description":""
            }
        ]
    },
    {
        "name":"Onix",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/pS97MTU.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Drowzee",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/oYSsVfz.png",
                "description":""
            }
        ]
    },
    {
        "name":"Hypno",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/IprLu9e.png",
                "description":""
            }
        ]
    },
    {
        "name":"Krabby",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Kingler",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/xm2n7vr.png",
                "description":""
            }
        ]
    },
    {
        "name":"Voltorb",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/RaTmeOw.png",
                "description":""
            }
        ]
    },
    {
        "name":"Electrode",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Exeggcute",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/wYVAsyS.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Exeggutor",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Cubone",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/ADhyNmu.png",
                "description":""
            }
        ]
    },
    {
        "name":"Marowak",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/HYp3wbo.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Hitmonlee",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Hitmonchan",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/15Pp9T3.png",
                "description":""
            }
        ]
    },
    {
        "name":"Lickitung",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/U8iQD4S.png",
                "description":""
            },{
                "src":"http://i.imgur.com/d9hZCKq.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Koffing",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/h3orGwd.png",
                "description":""
            },{
                "src":"http://i.imgur.com/l0XkR9S.png",
                "description":""
            }
        ]
    },
    {
        "name":"Weezing",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/Yp1iVyJ.png",
                "description":""
            }
        ]
    },
    {
        "name":"Rhyhorn",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/T8wV7V6.png",
                "description":""
            }
        ]
    },
    {
        "name":"Rhydon",
        "date":"",
        "img":[{
            "src":"http://i.imgur.com/KKbI0UJ.png",
            "description":""
        }
        ]
    },    
    {
        "name":"Chansey",
        "date":"",
        "img":[{
            "src":"http://i.imgur.com/jgDp5wv.png",
            "description":"Offering first aid in the streets"
        }
        ]
    },
    {
        "name":"Tangela",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Kangaskhan",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Horsea",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/JHu69Ly.png",
                "description":""
            }
        ]
    },
    {
        "name":"Seadra",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/Uz8Wfj1.png",
                "description":""
            }
        ]
    },
    {
        "name":"Goldeen",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Seaking",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/C1Ayl6c.png",
                "description":""
            }
        ]
    },
    {
        "name":"Staryu",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/zm5RDG9.png",
                "description":""
            }
        ]
    },
    {
        "name":"Starmie",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/YOS60I9.png",
                "description":""
            }
        ]
    },
    {
        "name":"Mr Mime",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Scyther",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Jynx",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/lW1TJd0.png",
                "description":""
            }
        ]
    },
    {
        "name":"Electabuzz",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/SFw1wx4.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Magmar",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Pinsir",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/Bcgxwha.png",
                "description":"Just being angry"
            }
        ]
    },
    {
        "name":"Tauros",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/0oudHad.png",
                "description":""
            },{
                "src":"http://i.imgur.com/VprBlS3.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Magikarp",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Gyarados",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/qf0u1wI.png",
                "description":""
            }
        ]
    },
    {
        "name":"Lapras",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/Jbr2HpT.png",
                "description":""
            }
        ]
    },
    {
        "name":"Ditto",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Eevee",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/Xk9DAax.png",
                "description":""
            }
        ]
    },
    {
        "name":"Vaporeon",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/oFJgHgc.png",
                "description":""
            }
        ]
    },
    {
        "name":"Jolteon",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Flareon",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Porygon",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/IMR5x3f.png",
                "description":""
            },{
                "src":"http://i.imgur.com/093j7cK.png",
                "description":"Burning in the heat"
            }
        ]
    },
    {
        "name":"Omanyte",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/3h4e04V.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Omaster",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Kabuto",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/AlEZP6a.png",
                "description":""
            }
        ]
    },
    {
        "name":"Kabutops",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/PFyZXOZ.png",
                "description":""
            }
        ]
    },
    {
        "name":"Aerodactyl",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/FAOMgat.png",
                "description":""
            },{
                "src":"http://i.imgur.com/EtKvl5C.png",
                "description":""
            },{
                "src":"http://i.imgur.com/Io6f9pg.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Snorlax",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/u8LsLan.png",
                "description":""
            },{
                "src":"http://i.imgur.com/X44N5N8.png",
                "description":""
            },{
                "src":"http://i.imgur.com/kNDvu1B.png",
                "description":""
            },{
                "src":"http://i.imgur.com/l8v21XA.png",
                "description":"Out enjoying some fresh air"
            }
        ]
    },
    {
        "name":"Articuno",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Zapdos",
        "date":"",
        "img":[
        ]
    },    
    {
        "name":"Moltres",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Dratini",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/L186e9M.png",
                "description":""
            }
        ]
    },
    {
        "name":"Dragonair",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/GIjAPr2.png",
                "description":""
            }
        ]
    },    
    {
        "name":"Dragonite",
        "date":"",
        "img":[{
                "src":"http://i.imgur.com/7kpDRT7.png",
                "description":"By Robson street"
            },{
                "src":"http://i.imgur.com/JdBg7mR.png",
                "description":"First Dragonite caught in the wild"
            },{
                "src":"http://i.imgur.com/C6Q4y29.png",
                "description":"In Pacific Center Mall"
            },{
                "src":"http://i.imgur.com/wJlaOYZ.png",
                "description":"Highest caught CP at 2967 and at 89% IV"
            }
        ]
    },
    {
        "name":"Mewtwo",
        "date":"",
        "img":[
        ]
    },
    {
        "name":"Mew",
        "date":"",
        "img":[
        ]
    }
]);