window["formatPokemonJSON"]([
    {
        "id":001,
        "gen":1,
        "name":"Bulbasaur",
        "src":"http://i.imgur.com/gmQKM0t.png",
        "thumbnail":"http://i.imgur.com/gmQKM0tb.png",
        "type":[{
                "type":"grass"
            },{
                "type":"poison"
        }],
        "favourite":"false"
    },
    {
        "id":002,
        "gen":1,
        "name":"Ivysaur",
        "src":"http://i.imgur.com/Vn6B4gE.png",
        "thumbnail":"http://i.imgur.com/Vn6B4gEb.png",
        "type":[{
                "type":"grass"
            },{
                "type":"poison"
        }],
        "favourite":"false"
    },    
    {
        "id":003,
        "gen":1,
        "name":"Venusaur",
        "src":"http://i.imgur.com/f5LFR6m.png",
        "thumbnail":"http://i.imgur.com/f5LFR6mb.png",
        "type":[{
                "type":"grass"
            },{
                "type":"poison"
        }],
        "favourite":"false"
    },
    {
        "id":004,
        "gen":1,
        "name":"Charmander",
        "src":"http://i.imgur.com/hXf3YiU.png",
        "thumbnail":"http://i.imgur.com/hXf3YiUb.png",
        "type":[{
            "type":"fire"
        }],
        "favourite":"false"
    },
    {
        "id":005,
        "gen":1,
        "name":"Charmeleon",
        "src":"http://i.imgur.com/dWB2iS3.png",
        "thumbnail":"http://i.imgur.com/dWB2iS3b.png",
        "type":[{
            "type":"fire"
        }],
        "favourite":"false"
    },    
    {
        "id":006,
        "gen":1,
        "name":"Charizard",
        "src":"http://i.imgur.com/OKXYsfy.png",
        "thumbnail":"http://i.imgur.com/OKXYsfyb.png",
        "type":[{
            "type":"fire"
        }],
        "favourite":"false"
    },
    {
        "id":007,
        "gen":1,
        "name":"Squirtle",
        "src":"http://i.imgur.com/6hc99aC.png",
        "thumbnail":"http://i.imgur.com/6hc99aCb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":008,
        "gen":1,
        "name":"Wartortle",
        "src":"http://i.imgur.com/l4fzHIm.png",
        "thumbnail":"http://i.imgur.com/l4fzHImb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },    
    {
        "id":009,
        "gen":1,
        "name":"Blastoise",
        "src":"http://i.imgur.com/B21Aalp.png",
        "thumbnail":"http://i.imgur.com/B21Aalpb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":010,
        "gen":1,
        "name":"Caterpie",
        "src":"http://i.imgur.com/OBiFiU1.png",
        "thumbnail":"http://i.imgur.com/OBiFiU1b.png",
        "type":[{
            "type":"bug"
        }],
        "favourite":"false"
    },
    {
        "id":011,
        "gen":1,
        "name":"Metapod",
        "src":"http://i.imgur.com/SAsd7ti.png",
        "thumbnail":"http://i.imgur.com/SAsd7tib.png",
        "type":[{
            "type":"bug"
        }],
        "favourite":"false"
    },
    {
        "id":012,
        "gen":1,
        "name":"Butterfree",
        "src":"http://i.imgur.com/u5pzd8t.png",
        "thumbnail":"http://i.imgur.com/u5pzd8tb.png",
        "type":[{
                "type":"bug"
            },{
                "type":"flying"
        }],
        "favourite":"false"
    },    
    {
        "id":013,
        "gen":1,
        "name":"Weedle",
        "src":"http://i.imgur.com/H0rvo4D.png",
        "thumbnail":"http://i.imgur.com/H0rvo4Db.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":014,
        "gen":1,
        "name":"Kakuna",
        "src":"http://i.imgur.com/ST75hO5.png",
        "thumbnail":"http://i.imgur.com/ST75hO5b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":015,
        "gen":1,
        "name":"Beedrill",
        "src":"http://i.imgur.com/m5wswlN.png",
        "thumbnail":"http://i.imgur.com/m5wswlNb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":016,
        "gen":1,
        "name":"Pidgey",
        "src":"http://i.imgur.com/sZNE462.png",
        "thumbnail":"http://i.imgur.com/sZNE462b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":017,
        "gen":1,
        "name":"Pidgeotto",
        "src":"http://i.imgur.com/BPkPbUh.png",
        "thumbnail":"http://i.imgur.com/BPkPbUhb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":018,
        "gen":1,
        "name":"Pidgeot",
        "src":"http://i.imgur.com/mmSkCMv.png",
        "thumbnail":"http://i.imgur.com/mmSkCMvb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":019,
        "gen":1,
        "name":"Rattata",
        "src":"http://i.imgur.com/YEq2CTx.png",
        "thumbnail":"http://i.imgur.com/YEq2CTxb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":020,
        "gen":1,
        "name":"Raticate",
        "src":"http://i.imgur.com/Zty1WNN.png",
        "thumbnail":"http://i.imgur.com/Zty1WNNb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":021,
        "gen":1,
        "name":"Spearow",
        "src":"http://i.imgur.com/VemAocD.png",
        "thumbnail":"http://i.imgur.com/VemAocDb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":022,
        "gen":1,
        "name":"Fearow",
        "src":"http://i.imgur.com/Hd0a419.png",
        "thumbnail":"http://i.imgur.com/Hd0a419b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":023,
        "gen":1,
        "name":"Ekans",
        "src":"http://i.imgur.com/IkjjPDF.png",
        "thumbnail":"http://i.imgur.com/IkjjPDFb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":024,
        "gen":1,
        "name":"Arbok",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":025,
        "gen":1,
        "name":"Pikachu",
        "src":"http://i.imgur.com/OUjC9UX.png",
        "thumbnail":"http://i.imgur.com/OUjC9UXb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":026,
        "gen":1,
        "name":"Raichu",
        "src":"http://i.imgur.com/qV5EKwf.png",
        "thumbnail":"http://i.imgur.com/qV5EKwfb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":027,
        "gen":1,
        "name":"Sandshrew",
        "src":"http://i.imgur.com/jsZJLAs.png",
        "thumbnail":"http://i.imgur.com/jsZJLAsb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":028,
        "gen":1,
        "name":"Sandslash",
        "src":"http://i.imgur.com/r2KWnhU.png",
        "thumbnail":"http://i.imgur.com/r2KWnhUb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":029,
        "gen":1,
        "name":"Nidoran♀",
        "src":"http://i.imgur.com/0xsItZ4.png",
        "thumbnail":"http://i.imgur.com/0xsItZ4b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":030,
        "gen":1,
        "name":"Nidorina",
        "src":"http://i.imgur.com/PFH2iRU.png",
        "thumbnail":"http://i.imgur.com/PFH2iRUb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":031,
        "gen":1,
        "name":"Nidoqueen",
        "src":"http://i.imgur.com/2xdXmwc.png",
        "thumbnail":"http://i.imgur.com/2xdXmwcb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":032,
        "gen":1,
        "name":"Nidoran♂",
        "src":"http://i.imgur.com/SKczujx.png",
        "thumbnail":"http://i.imgur.com/SKczujxb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":33,
        "gen":1,
        "name":"Nidorino",
        "src":"http://i.imgur.com/rDvAoRl.png",
        "thumbnail":"http://i.imgur.com/rDvAoRlb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":34,
        "gen":1,
        "name":"Nidoking",
        "src":"http://i.imgur.com/2zbHJhx.png",
        "thumbnail":"http://i.imgur.com/2zbHJhxb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":35,
        "gen":1,
        "name":"Clefairy",
        "src":"http://i.imgur.com/9PrW3IT.png",
        "thumbnail":"http://i.imgur.com/9PrW3ITb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":36,
        "gen":1,
        "name":"Clefable",
        "src":"http://i.imgur.com/sogf5EX.png",
        "thumbnail":"http://i.imgur.com/sogf5EXb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":37,
        "gen":1,
        "name":"Vulpix",
        "src":"http://i.imgur.com/j1kzr9h.png",
        "thumbnail":"http://i.imgur.com/j1kzr9hb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":38,
        "gen":1,
        "name":"Ninetales",
        "src":"http://i.imgur.com/HznJaWx.png",
        "thumbnail":"http://i.imgur.com/HznJaWxb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":39,
        "gen":1,
        "name":"Jigglypuff",
        "src":"http://i.imgur.com/q8dgZuQ.png",
        "thumbnail":"http://i.imgur.com/q8dgZuQb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":40,
        "gen":1,
        "name":"Wigglytuff",
        "src":"http://i.imgur.com/y5ISByQ.png",
        "thumbnail":"http://i.imgur.com/y5ISByQb.png",
        "type":[{
            "type":"normal"
        }],
        "favourite":"false"
    },
    {
        "id":41,
        "gen":1,
        "name":"Zubat",
        "src":"http://i.imgur.com/jpbLSkz.png",
        "thumbnail":"http://i.imgur.com/jpbLSkzb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":42,
        "gen":1,
        "name":"Golbat",
        "src":"http://i.imgur.com/ELja1Pa.png",
        "thumbnail":"http://i.imgur.com/ELja1Pab.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":43,
        "gen":1,
        "name":"Oddish",
        "src":"http://i.imgur.com/AuUNSTe.png",
        "thumbnail":"http://i.imgur.com/AuUNSTeb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":44,
        "gen":1,
        "name":"Gloom",
        "src":"http://i.imgur.com/EGuU3OY.png",
        "thumbnail":"http://i.imgur.com/EGuU3OYb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":45,
        "gen":1,
        "name":"Vileplume",
        "src":"http://i.imgur.com/arSvKJT.png",
        "thumbnail":"http://i.imgur.com/arSvKJTb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":46,
        "gen":1,
        "name":"Paras",
        "src":"http://i.imgur.com/Hw49p0Q.png",
        "thumbnail":"http://i.imgur.com/Hw49p0Qb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":47,
        "gen":1,
        "name":"Parasect",
        "src":"http://i.imgur.com/iS5bKnh.png",
        "thumbnail":"http://i.imgur.com/iS5bKnhb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":48,
        "gen":1,
        "name":"Venonat",
        "src":"http://i.imgur.com/ks8Urxe.png",
        "thumbnail":"http://i.imgur.com/ks8Urxeb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":49,
        "gen":1,
        "name":"Venomoth",
        "src":"http://i.imgur.com/Bs0Jy8x.png",
        "thumbnail":"http://i.imgur.com/Bs0Jy8xb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":50,
        "gen":1,
        "name":"Diglett",
        "src":"http://i.imgur.com/4w1Uti3.png",
        "thumbnail":"http://i.imgur.com/4w1Uti3b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":51,
        "gen":1,
        "name":"Dugtrio",
        "src":"http://i.imgur.com/onyeAzx.png",
        "thumbnail":"http://i.imgur.com/onyeAzxb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":52,
        "gen":1,
        "name":"Meowth",
        "src":"http://i.imgur.com/x9f0Fc0.png",
        "thumbnail":"http://i.imgur.com/x9f0Fc0b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":53,
        "gen":1,
        "name":"Persian",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":54,
        "gen":1,
        "name":"Psyduck",
        "src":"http://i.imgur.com/ve2elus.png",
        "thumbnail":"http://i.imgur.com/ve2elusb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":55,
        "gen":1,
        "name":"Golduck",
        "src":"http://i.imgur.com/V64yg8t.png",
        "thumbnail":"http://i.imgur.com/V64yg8tb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":56,
        "gen":1,
        "name":"Mankey",
        "src":"http://i.imgur.com/oozvqEV.png",
        "thumbnail":"http://i.imgur.com/oozvqEVb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":57,
        "gen":1,
        "name":"Primeape",
        "src":"http://i.imgur.com/kG0jIBe.png",
        "thumbnail":"http://i.imgur.com/kG0jIBeb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":58,
        "gen":1,
        "name":"Growlithe",
        "src":"http://i.imgur.com/vAnTRpc.png",
        "thumbnail":"http://i.imgur.com/vAnTRpcb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":59,
        "gen":1,
        "name":"Arcanine",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":60,
        "gen":1,
        "name":"Poliwag",
        "src":"http://i.imgur.com/1Q59xTC.png",
        "thumbnail":"http://i.imgur.com/1Q59xTCb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":61,
        "gen":1,
        "name":"Poliwhirl",
        "src":"http://i.imgur.com/PoDib1I.png",
        "thumbnail":"http://i.imgur.com/PoDib1Ib.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":62,
        "gen":1,
        "name":"Poliwrath",
        "src":"http://i.imgur.com/3fqTV0X.png",
        "thumbnail":"http://i.imgur.com/3fqTV0Xb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":63,
        "gen":1,
        "name":"Abra",
        "src":"http://i.imgur.com/cJDkdEl.png",
        "thumbnail":"http://i.imgur.com/cJDkdElb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":64,
        "gen":1,
        "name":"Kadabra",
        "src":"http://i.imgur.com/9u9f5Gc.png",
        "thumbnail":"http://i.imgur.com/9u9f5Gcb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":65,
        "gen":1,
        "name":"Alakazam",
        "src":"http://i.imgur.com/R636eI5.png",
        "thumbnail":"http://i.imgur.com/R636eI5b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":66,
        "gen":1,
        "name":"Machop",
        "src":"http://i.imgur.com/R3bFF6b.png",
        "thumbnail":"http://i.imgur.com/R3bFF6bb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":67,
        "gen":1,
        "name":"Machoke",
        "src":"http://i.imgur.com/zV6vP5c.png",
        "thumbnail":"http://i.imgur.com/zV6vP5cb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":68,
        "gen":1,
        "name":"Machamp",
        "src":"http://i.imgur.com/ifLwrYM.png",
        "thumbnail":"http://i.imgur.com/ifLwrYMb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":69,
        "gen":1,
        "name":"Bellsprout",
        "src":"http://i.imgur.com/wv0MKhT.png",
        "thumbnail":"http://i.imgur.com/wv0MKhTb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":70,
        "gen":1,
        "name":"Weepinbell",
        "src":"http://i.imgur.com/CHCzMhs.png",
        "thumbnail":"http://i.imgur.com/CHCzMhsb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":71,
        "gen":1,
        "name":"Victreebel",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":72,
        "gen":1,
        "name":"Tentacool",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":73,
        "gen":1,
        "name":"Tentacruel",
        "src":"http://i.imgur.com/GQoJebC.png",
        "thumbnail":"http://i.imgur.com/GQoJebCb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":74,
        "gen":1,
        "name":"Geodude",
        "src":"http://i.imgur.com/iqyDdje.png",
        "thumbnail":"http://i.imgur.com/iqyDdjeb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":75,
        "gen":1,
        "name":"Graveler",
        "src":"http://i.imgur.com/Ffvb1gu.png",
        "thumbnail":"http://i.imgur.com/Ffvb1gub.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":76,
        "gen":1,
        "name":"Golem",
        "src":"http://i.imgur.com/gW43rOY.png",
        "thumbnail":"http://i.imgur.com/gW43rOYb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":77,
        "gen":1,
        "name":"Ponyta",
        "src":"http://i.imgur.com/J10TMCZ.png",
        "thumbnail":"http://i.imgur.com/J10TMCZb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":78,
        "gen":1,
        "name":"Rapidash",
        "src":"http://i.imgur.com/TSGdCt6.png",
        "thumbnail":"http://i.imgur.com/TSGdCt6b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":79,
        "gen":1,
        "name":"Slowpoke",
        "src":"http://i.imgur.com/ZqifQf2.png",
        "thumbnail":"http://i.imgur.com/ZqifQf2b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":80,
        "gen":1,
        "name":"Slowbro",
        "src":"http://i.imgur.com/5zPBSrL.png",
        "thumbnail":"http://i.imgur.com/5zPBSrLb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":81,
        "gen":1,
        "name":"Magnemite",
        "src":"http://i.imgur.com/wTNVZlw.png",
        "thumbnail":"http://i.imgur.com/wTNVZlwb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":82,
        "gen":1,
        "name":"Magneton",
        "src":"http://i.imgur.com/8V3IwJE.png",
        "thumbnail":"http://i.imgur.com/8V3IwJEb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":83,
        "gen":1,
        "name":"Farfetch d",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":84,
        "gen":1,
        "name":"Doduo",
        "src":"http://i.imgur.com/ev7WLPw.png",
        "thumbnail":"http://i.imgur.com/ev7WLPwb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":85,
        "gen":1,
        "name":"Dodrio",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":86,
        "gen":1,
        "name":"Seel",
        "src":"http://i.imgur.com/KZAJhYO.png",
        "thumbnail":"http://i.imgur.com/KZAJhYOb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":87,
        "gen":1,
        "name":"Dewgong",
        "src":"http://i.imgur.com/7jILGeH.png",
        "thumbnail":"http://i.imgur.com/7jILGeHb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":88,
        "gen":1,
        "name":"Grimer",
        "src":"http://i.imgur.com/eJyKkJM.png",
        "thumbnail":"http://i.imgur.com/eJyKkJMb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":89,
        "gen":1,
        "name":"Muk",
        "src":"http://i.imgur.com/tztKvPO.png",
        "thumbnail":"http://i.imgur.com/tztKvPOb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":90,
        "gen":1,
        "name":"Shellder",
        "src":"http://i.imgur.com/XM68smG.png",
        "thumbnail":"http://i.imgur.com/XM68smGb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":91,
        "gen":1,
        "name":"Cloyster",
        "src":"http://i.imgur.com/gH9FZIh.png",
        "thumbnail":"http://i.imgur.com/gH9FZIhb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":92,
        "gen":1,
        "name":"Gastly",
        "src":"http://i.imgur.com/GAkvjru.png",
        "thumbnail":"http://i.imgur.com/GAkvjrub.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":93,
        "gen":1,
        "name":"Haunter",
        "src":"http://i.imgur.com/f56Wylk.png",
        "thumbnail":"http://i.imgur.com/f56Wylkb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":94,
        "gen":1,
        "name":"Gengar",
        "src":"http://i.imgur.com/z12vy32.png",
        "thumbnail":"http://i.imgur.com/z12vy32b.png",
        "type":[{
            "type":"ghost"
        }],
        "favourite":"false"
    },
    {
        "id":95,
        "gen":1,
        "name":"Onix",
        "src":"http://i.imgur.com/4ecE98v.png",
        "thumbnail":"http://i.imgur.com/4ecE98vb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":96,
        "gen":1,
        "name":"Drowzee",
        "src":"http://i.imgur.com/G6k7lpk.png",
        "thumbnail":"http://i.imgur.com/G6k7lpkb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":97,
        "gen":1,
        "name":"Hypno",
        "src":"http://i.imgur.com/C9I42jB.png",
        "thumbnail":"http://i.imgur.com/C9I42jBb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":98,
        "gen":1,
        "name":"Krabby",
        "src":"http://i.imgur.com/GqpNEe9.png",
        "thumbnail":"http://i.imgur.com/GqpNEe9b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":99,
        "gen":1,
        "name":"Kingler",
        "src":"http://i.imgur.com/JVSTU3v.png",
        "thumbnail":"http://i.imgur.com/JVSTU3vb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":100,
        "gen":1,
        "name":"Voltorb",
        "src":"http://i.imgur.com/6MOvuSC.png",
        "thumbnail":"http://i.imgur.com/6MOvuSCb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":101,
        "gen":1,
        "name":"Electrode",
        "src":"http://i.imgur.com/9LvZMDk.png",
        "thumbnail":"http://i.imgur.com/9LvZMDkb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":102,
        "gen":1,
        "name":"Exeggcute",
        "src":"http://i.imgur.com/wn2aPmK.png",
        "thumbnail":"http://i.imgur.com/wn2aPmKb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":103,
        "gen":1,
        "name":"Exeggutor",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":104,
        "gen":1,
        "name":"Cubone",
        "src":"http://i.imgur.com/4IAH40e.png",
        "thumbnail":"http://i.imgur.com/4IAH40eb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":105,
        "gen":1,
        "name":"Marowak",
        "src":"http://i.imgur.com/PpcSG4k.png",
        "thumbnail":"http://i.imgur.com/PpcSG4kb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":106,
        "gen":1,
        "name":"Hitmonlee",
        "src":"http://i.imgur.com/HjGjhKX.png",
        "thumbnail":"http://i.imgur.com/HjGjhKXb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":107,
        "gen":1,
        "name":"Hitmonchan",
        "src":"http://i.imgur.com/uPLPLJO.png",
        "thumbnail":"http://i.imgur.com/uPLPLJOb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":108,
        "gen":1,
        "name":"Lickitung",
        "src":"http://i.imgur.com/xOmZOX7.png",
        "thumbnail":"http://i.imgur.com/xOmZOX7b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":109,
        "gen":1,
        "name":"Koffing",
        "src":"http://i.imgur.com/ZOh5txo.png",
        "thumbnail":"http://i.imgur.com/ZOh5txob.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":110,
        "gen":1,
        "name":"Weezing",
        "src":"http://i.imgur.com/QGnsbph.png",
        "thumbnail":"http://i.imgur.com/QGnsbphb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":111,
        "gen":1,
        "name":"Rhyhorn",
        "src":"http://i.imgur.com/PY7HrLY.png",
        "thumbnail":"http://i.imgur.com/PY7HrLYb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":112,
        "gen":1,
        "name":"Rhydon",
        "src":"http://i.imgur.com/qAR8eMa.png",
        "thumbnail":"http://i.imgur.com/qAR8eMab.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":113,
        "gen":1,
        "name":"Chansey",
        "src":"http://i.imgur.com/OLaeySo.png",
        "thumbnail":"http://i.imgur.com/OLaeySob.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":114,
        "gen":1,
        "name":"Tangela",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":115,
        "gen":1,
        "name":"Kangaskhan",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":116,
        "gen":1,
        "name":"Horsea",
        "src":"http://i.imgur.com/eeSGaVe.png",
        "thumbnail":"http://i.imgur.com/eeSGaVeb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":117,
        "gen":1,
        "name":"Seadra",
        "src":"http://i.imgur.com/U2W3D9X.png",
        "thumbnail":"http://i.imgur.com/U2W3D9Xb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":118,
        "gen":1,
        "name":"Goldeen",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },    
    {
        "id":119,
        "gen":1,
        "name":"Seaking",
        "src":"http://i.imgur.com/DprDhii.png",
        "thumbnail":"http://i.imgur.com/DprDhiib.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":120,
        "gen":1,
        "name":"Staryu",
        "src":"http://i.imgur.com/vOThjKI.png",
        "thumbnail":"http://i.imgur.com/vOThjKIb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":121,
        "gen":1,
        "name":"Starmie",
        "src":"http://i.imgur.com/qH1dNZd.png",
        "thumbnail":"http://i.imgur.com/qH1dNZdb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":122,
        "gen":1,
        "name":"Mr Mime",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":123,
        "gen":1,
        "name":"Scyther",
        "src":"http://i.imgur.com/3kcggvR.png",
        "thumbnail":"http://i.imgur.com/3kcggvRb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":124,
        "gen":1,
        "name":"Jynx",
        "src":"http://i.imgur.com/BdwjjLn.png",
        "thumbnail":"http://i.imgur.com/BdwjjLnb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":125,
        "gen":1,
        "name":"Electabuzz",
        "src":"http://i.imgur.com/pjLTbWl.png",
        "thumbnail":"http://i.imgur.com/pjLTbWlb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":126,
        "gen":1,
        "name":"Magmar",
        "src":"http://i.imgur.com/CvUgXS0.png",
        "thumbnail":"http://i.imgur.com/CvUgXS0b.png",
        "type":[{
            "type":"fire"
        }],
        "favourite":"false"
    },
    {
        "id":127,
        "gen":1,
        "name":"Pinsir",
        "src":"http://i.imgur.com/Cv4a9Z6.png",
        "thumbnail":"http://i.imgur.com/Cv4a9Z6b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":128,
        "gen":1,
        "name":"Tauros",
        "src":"http://i.imgur.com/spvrBZi.png",
        "thumbnail":"http://i.imgur.com/spvrBZib.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":129,
        "gen":1,
        "name":"Magikarp",
        "src":"http://i.imgur.com/cm1UGr4.png",
        "thumbnail":"http://i.imgur.com/cm1UGr4b.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":130,
        "gen":1,
        "name":"Gyarados",
        "src":"http://i.imgur.com/XpyglX6.png",
        "thumbnail":"http://i.imgur.com/XpyglX6b.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":131,
        "gen":1,
        "name":"Lapras",
        "src":"http://i.imgur.com/DGVXjMs.png",
        "thumbnail":"http://i.imgur.com/DGVXjMsb.png",
        "type":[{
            "type":"ice"
        }],
        "favourite":"false"
    },
    {
        "id":132,
        "gen":1,
        "name":"Ditto",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"normal"
        }],
        "favourite":"false"
    },    
    {
        "id":133,
        "gen":1,
        "name":"Eevee",
        "src":"http://i.imgur.com/p3jAGTw.png",
        "thumbnail":"http://i.imgur.com/p3jAGTwb.png",
        "type":[{
            "type":"normal"
        }],
        "favourite":"false"
    },
    {
        "id":134,
        "gen":1,
        "name":"Vaporeon",
        "src":"http://i.imgur.com/TkixlEZ.png",
        "thumbnail":"http://i.imgur.com/TkixlEZb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":135,
        "gen":1,
        "name":"Jolteon",
        "src":"http://i.imgur.com/Qb2DS9b.png",
        "thumbnail":"http://i.imgur.com/Qb2DS9bb.png",
        "type":[{
            "type":"electric"
        }],
        "favourite":"false"
    },    
    {
        "id":136,
        "gen":1,
        "name":"Flareon",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"fire"
        }],
        "favourite":"false"
    },
    {
        "id":137,
        "gen":1,
        "name":"Porygon",
        "src":"http://i.imgur.com/CaD2lHx.png",
        "thumbnail":"http://i.imgur.com/CaD2lHxb.png",
        "type":[{
            "type":"normal"
        }],
        "favourite":"false"
    },
    {
        "id":138,
        "gen":1,
        "name":"Omanyte",
        "src":"http://i.imgur.com/IMB7SEu.png",
        "thumbnail":"http://i.imgur.com/IMB7SEub.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },    
    {
        "id":139,
        "gen":1,
        "name":"Omaster",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":140,
        "gen":1,
        "name":"Kabuto",
        "src":"http://i.imgur.com/FpJDYnT.png",
        "thumbnail":"http://i.imgur.com/FpJDYnTb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":141,
        "gen":1,
        "name":"Kabutops",
        "src":"http://i.imgur.com/wNpO7Dv.png",
        "thumbnail":"http://i.imgur.com/wNpO7Dvb.png",
        "type":[{
            "type":"water"
        }],
        "favourite":"false"
    },
    {
        "id":142,
        "gen":1,
        "name":"Aerodactyl",
        "src":"http://i.imgur.com/h3j14R9.png",
        "thumbnail":"http://i.imgur.com/h3j14R9b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":143,
        "gen":1,
        "name":"Snorlax",
        "src":"http://i.imgur.com/hQedY6D.png",
        "thumbnail":"http://i.imgur.com/hQedY6Db.png",
        "type":[{
            "type":"normal"
        }],
        "favourite":"false"
    },
    {
        "id":144,
        "gen":1,
        "name":"Articuno",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":145,
        "gen":1,
        "name":"Zapdos",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":146,
        "gen":1,
        "name":"Moltres",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":147,
        "gen":1,
        "name":"Dratini",
        "src":"http://i.imgur.com/Q6Jh5Ae.png",
        "thumbnail":"http://i.imgur.com/Q6Jh5Aeb.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":148,
        "gen":1,
        "name":"Dragonair",
        "src":"http://i.imgur.com/38cMyq8.png",
        "thumbnail":"http://i.imgur.com/38cMyq8b.png",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },    
    {
        "id":149,
        "gen":1,
        "name":"Dragonite",
        "src":"http://i.imgur.com/Mpr5PWs.png",
        "thumbnail":"http://i.imgur.com/Mpr5PWsb.png",
        "type":[{
            "type":"dragon"
        }],
        "favourite":"false"
    },
    {
        "id":150,
        "gen":1,
        "name":"Mewtwo",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    },
    {
        "id":151,
        "gen":1,
        "name":"Mew",
        "src":"",
        "thumbnail":"",
        "type":[{
            "type":"grass"
        }],
        "favourite":"false"
    }
]);